-- SERVICE CATEGORIES
CREATE TABLE service_categories (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ADD CATEGORY RELATION TO SERVICES
ALTER TABLE services
ADD COLUMN category_id BIGINT DEFAULT NULL,
ADD CONSTRAINT fk_services_category
  FOREIGN KEY (category_id)
  REFERENCES service_categories(id)
  ON DELETE SET NULL;
