SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS courier_assignments;
DROP TABLE IF EXISTS status_history;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;
